name: Hello
defaults:
  - scope:
      type: "posts"
    values:
      permalink: /posts/:title.html
exclude:
  - Debug/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - ossutil64
  - package.json
  - package-lock.json
  - "*.less"
  - "*.psd"
repository: Xzonn/Test