name: Hello
defaults:
  - scope:
      type: "posts"
    values:
      permalink: /posts/:title.html
exclude:
  - Debug/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - ossutil64
  - package.json
  - package-lock.json
  - "*.less"
  - "*.psd"
repository: Xzonn/Test
sass:
  sass_dir: assets/css
  load_paths: 
    - assets/css
    - node_modules/bootstrap/scss
  sourcemap: always
  style: compressed
plugins:
  - jekyll-readme-index