author: Xzonn
baseurl: test
description: 这是一个测试。
exclude:
  - Debug/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
lsi: true
name: 测试
theme: minima
title: 测试