name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Commit Information
        id: commit
        run: |
          echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
          echo "changed_assets=$(git diff --name-only HEAD..HEAD~1 | Select-String -Pattern 'assets')" >> GITHUB_OUTPUT
          echo "changed_md=$(git diff --name-only HEAD..HEAD~1 | Select-String -Pattern '\.md$')" >> GITHUB_OUTPUT
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Npm
        run: |
          npm install
      - name: Build Site
        run: |
          bundle exec jekyll build --trace --profile --baseurl "${{ steps.pages.outputs.base_path }}"
          echo "${{ steps.commit.outputs.commit_message }}"
          echo "${{ steps.commit.outputs.changed_assets }}"
          echo "${{ steps.commit.outputs.changed_md }}"
        env:
          JEKYLL_ENV: aliyun
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "README.md"
          body: |
            这是一个

            测试！
          name: "${{ steps.commit.outputs.commit_message }}"
          tag: publish
          token: ${{ secrets.GITHUB_TOKEN }}