name: Download

on:
  push:
    branches: 
      - master

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Commit ID
        id: commit_id
        run: echo "::set-output name=commit_id::commit-$(git rev-parse --short HEAD)"
      - run: echo "${{ steps.commit_id.outputs.commit_id }}"
      - uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: Patches
          path: |
            A/C-1.txt
            B/C-2.txt
      - uses: ncipollo/release-action@v1
        continue-on-error: true
        with:
          allowUpdates: true
          artifacts: "A/C-1.txt,B/C-2.txt"
          body: "测试。"
          name: "测试"
          tag: ${{ steps.commit_id.outputs.commit_id }}
          token: ${{ secrets.GITHUB_TOKEN }}