name: Download

on:
  push:
    branches: 
      - master

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Commit Information
        id: commit
        run: |
          echo "::set-output name=commit_id::commit-$(git rev-parse --short HEAD)"
          echo "::set-output name=commit_message::$(git log -1 --pretty=%B)"
      - uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: Patches
          path: |
            A/C-1.txt
            B/C-2.txt
      - uses: ncipollo/release-action@v1
        continue-on-error: true
        with:
          allowUpdates: true
          artifacts: "A/C-1.txt,B/C-2.txt"
          bodyFile: Readme.md
          commit: dist
          name: ${{ steps.commit.outputs.commit_message }}
          tag: action-${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}