name: Download

on:
  push:
    branches: 
      - master

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: Patches
          path: |
            A/C-1.txt
            B/C-2.txt
      - uses: svenstaro/upload-release-action@v2
        continue-on-error: true
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*/C-*.txt"
          tag: ${{ github.sha }}
          overwrite: true
          file_glob: true