name: Publish

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: html
          path: html
      - name: Upload
        run: |
          ls
          ls html