name: Test branch

on:
  push:
    branches: 
      - test

jobs:
  random:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 1
          path: master
      - run: |
          pushd master
          echo $RANDOM >> $RANDOM.txt
          git add -A
          git -c user.name=GitHub -c user.email=noreply@github.com commit -m "Update"
          git push
          popd
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Xzonn/Test/.github/workflows/publish.yml@master