name: Build and Publish

on:
  push:
    branches: 
      - master
  workflow_call:

jobs:
  build:
    uses: Xzonn/Test/.github/workflows/build.yml@master
  
  publish:
    uses: Xzonn/Test/.github/workflows/publish.yml@master
